version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - API_ENDPOINT=https://jsonplaceholder.typicode.com/posts
      - SOURCE_NAME=placeholder_api
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DATABASE=logs
      - MONGO_COLLECTION=posts
      - FETCH_INTERVAL=5m
      - SERVER_PORT=8080
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: